name: uply
description: HackHers 2020 project | Futuristic Job Applying Process
version: 1.0.0+1
authors:
  - Dhruvil, Julia, and Manthan

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  groovin_material_icons: ^1.1.6
  humanitarian_icons: ^0.1.0
  flutter_launcher_icons: ^0.7.4
  font_awesome_flutter: ^8.5.0
  keyboard_avoider: ^0.1.2
  provider: ^4.0.2
  path_provider: ^1.4.0
  shared_preferences: ^0.5.2+1
  http: ^0.12.0+2
  json_annotation: ^3.0.1
  url_launcher: ^5.0.2
  arcore_flutter_plugin:
    git:
      url: git://github.com/giandifra/arcore_flutter_plugin.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  json_serializable: ^3.2.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon_transparent.png"


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - mock_data/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf